module.exports={
    api:{
            host:'192.168.10.254',
            port:'3000'
        },
    db:{
        host:'localhost',
        user:'root',
        password:'Hello@158.cn',
        port:'3306',
        database:'db_example'
    }
}